DROP DATABASE IF EXISTS db_copa;
CREATE DATABASE IF NOT EXISTS db_copa;
USE db_copa;

CREATE TABLE IF NOT EXISTS tb_usuario(
	IDUsuario INT AUTO_INCREMENT PRIMARY KEY,
    Nome_Usuario VARCHAR(255) NOT NULL,
    Senha_Usuario VARCHAR(255) NOT NULL,
    CPF_Usuario VARCHAR(11) NOT NULL,
    Tipo_Usuario CHAR(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_time(
	IDTime INT AUTO_INCREMENT PRIMARY KEY,
    Nome_Time VARCHAR(255) NOT NULL,
    Estadio VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS tb_jogador(
	IDJogador INT AUTO_INCREMENT PRIMARY KEY,
    Nome_Jogador VARCHAR(255) NOT NULL,
    Posicao_Jogador VARCHAR(255) NOT NULL
);
