DROP DATABASE IF EXISTS db_copa;
CREATE DATABASE IF NOT EXISTS db_copa;
USE db_copa;

CREATE TABLE IF NOT EXISTS tb_usuario(
	IDUsuario INT AUTO_INCREMENT PRIMARY KEY,
    Nome_Usuario VARCHAR(255) NOT NULL,
    CPF_Usuario VARCHAR(11) NOT NULL,
    Tipo_Usuario CHAR(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS tb_time(
	IDTime INT AUTO_INCREMENT PRIMARY KEY,
    Nome_Time VARCHAR(255) NOT NULL,
    Data_Fundacao DATE NOT NULL,
    Estadio VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS tb_jogador(
	IDJogador INT AUTO_INCREMENT PRIMARY KEY,
    Nome_Jogador VARCHAR(255) NOT NULL,
    Data_Nascimento DATE NOT NULL, 
    Posicao_Jogador VARCHAR(255) NOT NULL,
    IDTime INT NOT NULL,
    CONSTRAINT Fk_ID_Time FOREIGN KEY(IDTime) REFERENCES tb_time(IDTime)
);

CREATE TABLE IF NOT EXISTS tb_grupo(
	IDGrupo CHAR(1) PRIMARY KEY,
    IDTime1 INT NOT NULL,
    IDTime2 INT NOT NULL,
    IDTime3 INT NOT NULL,
    IDTime4 INT NOT NULL,
    CONSTRAINT Fk_ID_Time1 FOREIGN KEY(IDTime1) REFERENCES tb_time(IDTime),
    CONSTRAINT Fk_ID_Time2 FOREIGN KEY(IDTime2) REFERENCES tb_time(IDTime),
    CONSTRAINT Fk_ID_Time3 FOREIGN KEY(IDTime3) REFERENCES tb_time(IDTime),
    CONSTRAINT Fk_ID_Time4 FOREIGN KEY(IDTime4) REFERENCES tb_time(IDTime)
);